name: Codacy Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  codacy-analysis:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run Codacy analysis
      run: |
        curl -Ls https://coverage.codacy.com/get.sh | bash
      env:
        CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
